### ISSUE TITLE
能开放elasticsearch 中文文档吗？感谢！ 

### ISSUE THREAD

**Issue by feiguoL** [icopy-site/icopy-site.github.io#14]
原文档地址：https://www.elastic.co/guide/en/elasticsearch/reference

另外白名单里面有些网站好像已经失效了，望校验一下，多谢！

**Comment by chenjiajia** [comment]
elastic  比較在意版權， 爲了避免可能的版權問題，從白名單刪掉了
https://github.com/elastic/docs
The documents produced by this build process may be published only on http://www.elastic.co. They may not be published in any other form or on any other website without explicit permission.
