### ISSUE TITLE
能把广告放到下面吗？

### ISSUE THREAD

**Issue by Hanggi** [icopy-site/icopy-site.github.io#17]
谢谢

**Comment by chenjiajia** [comment]
现在代码里是根据第一个p标签插入的广告，试过几个不同逻辑效果都不太好，还是挺多网站广告位置不太合理，影响阅读了抱歉，装个adblock插件吧，直接屏蔽google广告

**Comment by yuyuanqiu** [comment]
希望能把贵站的网址logo改成静态图标，一闪一闪的有点影响阅读体验

**Comment by yuyuanqiu** [comment]
> 现在代码里是根据第一个p标签插入的广告，试过几个不同逻辑效果都不太好，还是挺多网站广告位置不太合理，影响阅读了抱歉，装个adblock插件吧，直接屏蔽google广告

**希望能把贵站的网址logo改成静态图标，一闪一闪的有点影响阅读体验**
