### ISSUE TITLE
请添加spring cloud

### ISSUE THREAD

**Issue by goolnen** [icopy-site/icopy-site.github.io#4]
例如：https://cloud.spring.io/spring-cloud-static/Greenwich.SR3/single/spring-cloud.html
建议可将"spring"设为关键字，spring家族还有些其他文档也需要

**Comment by XuDaojie** [comment]
我看spring文档域名现在大部分是https://docs.spring.io，直接添加https://cloud.spring.io就差不多了

**Comment by chenjiajia** [comment]
已添加cloud.spring.io 白名单
