### ISSUE TITLE
怎么才能禁用？现在一打开网站就是这东西

### ISSUE THREAD

**Issue by JyHu** [icopy-site/icopy-site.github.io#5]
都不知道从哪儿就有了这个自动翻译的

**Comment by liubiantao** [comment]
我维护一个这些垃圾的列表，里面有屏蔽的教程 https://github.com/liubiantao/uBlacklist-Websites

**Comment by JyHu** [comment]
> 我维护一个这些垃圾的列表，里面有屏蔽的教程 https://github.com/liubiantao/uBlacklist-Websites

搞不懂的是，我又没有安装它相关的东西，也没有主动的引入，为啥他就能直接的过来给我翻译了呢？

**Comment by liubiantao** [comment]
有截图吗？不明白你说的什么意思。

**Comment by liubiantao** [comment]
1. 如果你打开任意外文网站，都被翻译了，检查一下你浏览器的自动翻译功能。比如 Chrome 自带谷歌翻译，看看你地址栏是不是有个翻译按钮。

2. 如果你从搜索引擎里打开一个网页，看到都是翻译的内容，是因为站长在服务端就翻译好了，你看到的翻译后的内容就是这个网站本身的内容

3. 如果你说你自己搭建的网站都被翻译了...你都会搭建网站了，应该不用我教你。
