### ISSUE TITLE
【紧急】将https://developer.apple.com从白名单中删除

### ISSUE THREAD

**Issue by Hui1122** [icopy-site/icopy-site.github.io#9]
陈佳佳你好，我们已向你Gmail邮箱多次致函，请将https://developer.apple.com从白名单中删除，停止运营镜像网站https://s0developer0apple0com.icopy.site/

**Comment by Hui1122** [comment]
@chenjiajia

**Comment by chenjiajia** [comment]
抱歉,没有及时看到
